### ISSUE TITLE
Diameter of Binary Tree JAVA

### ISSUE THREAD

**Issue by akshaywakhare** [dark-coder-cat/Hactoberfest2021#131]

**Comment by akshaywakhare** [comment]
> > can I work on this issue?
> 
> @akshaywakhare Are you still working on this? [If not replied in 24 hrs I'll assign to @prakhar-198 ]

Its been completed and submitted

**Comment by akshaywakhare** [comment]
Shall I close the issue? @dark-coder-cat

**Comment by dark-coder-cat** [comment]
> > > can I work on this issue?
> > 
> > @akshaywakhare Are you still working on this? [If not replied in 24 hrs I'll assign to @prakhar-198 ]
> 
> Are you assigning me?

You both can still work on it. Just name the file like `filename_username.extension` as to avoid duplicates.
