### ISSUE TITLE
Arrange all elements of Array (Negative n Positive Numbers separately) as it is entered by the user.

### ISSUE THREAD

**Issue by Ayushagr145** [dark-coder-cat/Hactoberfest2021#289]
Please assign me this task for the HactoberFest-2021

**Comment by tokyo-arch** [comment]
kindly assign this issue to me .
I will do it in Java

**Comment by gssandhu143** [comment]
kindly assign it to me, i will do it in java and try to give the most optimal solution.

**Comment by tokyo-arch** [comment]
please check and merge #376

**Comment by pragyag15** [comment]
Hi, I'd like to work on this issue, can you assign this to me?
