### ISSUE TITLE
Convert an Entered text to a Cipher text in java

### ISSUE THREAD

**Issue by Ayushagr145** [dark-coder-cat/Hactoberfest2021#321]
Please Assign me this task for Hactoberfest-2021

**Comment by Ayushagr145** [comment]
Assign this task to me as soon as possible so that I can work on it

**Comment by dark-coder-cat** [comment]
> Assign this task to me as soon as possible so that I can work on it 

Sorry for late assign😅

**Comment by mehulthuletiyaofficial** [comment]
Please, assign to fast ⏩🙏🏻...

**Comment by pragyag15** [comment]
Hi, I'd like to work on this issue, can you assign this to me?
