### ISSUE TITLE
Django chatting site 

### ISSUE THREAD

**Issue by TUSHAR-VERMA-star** [dark-coder-cat/Hactoberfest2021#450]
![image](https://user-images.githubusercontent.com/83601065/138559278-1842c18f-21fc-4b55-b628-936e0c3efd14.png)
![image](https://user-images.githubusercontent.com/83601065/138559285-59420b0d-f2ee-44b2-adf1-58c2fad08ea9.png)
please assign it to me !!

**Comment by Ciphrox** [comment]
> ![image](https://user-images.githubusercontent.com/83601065/138559278-1842c18f-21fc-4b55-b628-936e0c3efd14.png)
> ![image](https://user-images.githubusercontent.com/83601065/138559285-59420b0d-f2ee-44b2-adf1-58c2fad08ea9.png)
> please assign it to me !!

This repo has been excluded from Hacktoberfest so any pr won't be counted

**Comment by TUSHAR-VERMA-star** [comment]
ok np
